### ISSUE TITLE
Port the Project to Godot 3.1

### ISSUE THREAD

**Issue by asheraryam** [crystal-bit/triple-triad-godot#1]
Opening an issue to see if a PR is welcome.

I've worked with the 3.1 version of the engine for several months now, so I'd like to try to port it and see if there will be any blocking issue with that.

I'd also like to take a look at the other ToDo features (randomizing the cards, ending screen for battles) so feel free to open an issue if you'd like help with that too.

**Comment by davcri** [comment]
Hi @asheraryam! Thank you very much for this issue.

If you would like to work on the Godot 3.1 porting, I would be *very glad* to see it and help along the way!

For the other features: I just released the [v1.1](https://github.com/crystal-bit/triple-triad-godot/releases/tag/v1.1) which includes cards randomizing and ending screens. Even if they are rough, they works and it makes the game less boring (before it was a 30second experience).

**Comment by davcri** [comment]
I created a [v3.1 branch](https://github.com/crystal-bit/triple-triad-godot/tree/v3.1).  

It seems that everything is working out-of-the-box :sweat_smile: 
I'm considering adding type signatures and doing some refactoring on this new branch before merging it to master.

**Comment by davcri** [comment]
v3.1 branch is now merged in master!
