### ISSUE TITLE
Keep current rules when playing a new game

### ISSUE THREAD

**Issue by sleepyspip** [crystal-bit/triple-triad-godot#8]
Currently the Play Again button on the Result screens (Results.tscn) starts a new game with the default set of rules, not the set of rules used for the previous game. So if after playing a game without the rule "Open", the player starts a new game this way, the new game will be using the rule "Open".

This is due to calling the new game scene without passing any rule dictionary as parameter:
https://github.com/crystal-bit/triple-triad-godot/blob/b4e1fcbdb0f3bd5ee8e301532f37155057b9ee0a/GameScenes/BattleResults/PlayAgain.gd#L4

**Comment by davcri** [comment]
Fixed in #9, thanks!
